name: Science News Bot (Daily)

on:
  schedule:
    - cron: "0 13 * * *"  # 13:00 UTC (~9:00 AM America/New_York)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dry-run preview
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python science-news-twitter-bot.py --dry-run --max 10 | tee preview.txt

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview
          path: preview.txt

      - name: Post to X (disabled by default)
        if: ${{ false }} # change to true to enable automatic posting
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          SCI_BOT_RECENCY_DAYS: "7"
          SCI_BOT_CONFIG: "config.json"
        run: |
          python science-news-twitter-bot.py --post --max 10
